-- New tool definitions: document parsing, media, translation, coding, web capture, data extraction
INSERT OR IGNORE INTO tool_definitions (id, name, description, category, parameters_schema) VALUES
  ('tool_parse_document', 'parse_document', 'Leggi e analizza documenti PDF, DOCX, XLSX, CSV con estrazione testo strutturato', 'filesystem', '{"type":"object","properties":{"path":{"type":"string","description":"Percorso del documento (PDF, DOCX, XLSX, CSV)"},"pages":{"type":"string","description":"Range pagine per PDF (es. 1-5)"}},"required":["path"]}'),
  ('tool_generate_image', 'generate_image', 'Genera immagini con DALL-E 3 da una descrizione testuale', 'media', '{"type":"object","properties":{"prompt":{"type":"string","description":"Descrizione dell''immagine da generare"},"size":{"type":"string","enum":["1024x1024","1792x1024","1024x1792"],"default":"1024x1024"},"quality":{"type":"string","enum":["standard","hd"],"default":"standard"},"style":{"type":"string","enum":["vivid","natural"],"default":"vivid"}},"required":["prompt"]}'),
  ('tool_analyze_image', 'analyze_image', 'Analizza un''immagine con AI vision (Gemini/GPT-4o) e descrivi il contenuto', 'media', '{"type":"object","properties":{"path":{"type":"string","description":"Percorso dell''immagine da analizzare"},"prompt":{"type":"string","description":"Domanda o istruzione per l''analisi","default":"Descrivi dettagliatamente cosa vedi in questa immagine."}},"required":["path"]}'),
  ('tool_text_to_speech', 'text_to_speech', 'Converti testo in audio parlato (OpenAI TTS)', 'media', '{"type":"object","properties":{"text":{"type":"string","description":"Testo da convertire in audio"},"voice":{"type":"string","enum":["alloy","echo","fable","onyx","nova","shimmer"],"default":"alloy","description":"Voce da utilizzare"},"speed":{"type":"number","minimum":0.25,"maximum":4.0,"default":1.0,"description":"Velocita parlato"}},"required":["text"]}'),
  ('tool_speech_to_text', 'speech_to_text', 'Trascrivi audio in testo con OpenAI Whisper (MP3, WAV, M4A, WebM, MP4)', 'media', '{"type":"object","properties":{"path":{"type":"string","description":"Percorso del file audio"},"language":{"type":"string","description":"Codice lingua ISO (es. it, en, es)"},"prompt":{"type":"string","description":"Contesto per migliorare la trascrizione"}},"required":["path"]}'),
  ('tool_translate_text', 'translate_text', 'Traduci testo tra lingue con AI (supporta tutte le lingue principali)', 'language', '{"type":"object","properties":{"text":{"type":"string","description":"Testo da tradurre"},"target_language":{"type":"string","description":"Lingua di destinazione (es. inglese, francese, tedesco, giapponese)"},"source_language":{"type":"string","description":"Lingua sorgente (opzionale, auto-detect)"}},"required":["text","target_language"]}'),
  ('tool_generate_code', 'generate_code', 'Genera codice sorgente da una descrizione e opzionalmente lo esegue', 'coding', '{"type":"object","properties":{"description":{"type":"string","description":"Descrizione di cosa deve fare il codice"},"language":{"type":"string","enum":["javascript","typescript","python","bash","html","css","sql","go","rust","java","cpp","ruby","php"],"default":"javascript"},"execute":{"type":"boolean","default":false,"description":"Eseguire il codice generato"},"filename":{"type":"string","description":"Nome file (opzionale)"}},"required":["description","language"]}'),
  ('tool_screenshot_url', 'screenshot_url', 'Cattura screenshot di una pagina web con Puppeteer', 'web', '{"type":"object","properties":{"url":{"type":"string","description":"URL della pagina da catturare"},"viewport":{"type":"string","enum":["desktop","tablet","mobile"],"default":"desktop"},"full_page":{"type":"boolean","default":true,"description":"Cattura pagina intera o solo viewport"}},"required":["url"]}'),
  ('tool_extract_data', 'extract_data', 'Estrai dati strutturati (JSON) da testo libero usando AI', 'data', '{"type":"object","properties":{"text":{"type":"string","description":"Testo da cui estrarre dati"},"schema":{"type":"string","description":"Descrizione dello schema JSON desiderato (es. {nome, email, telefono})"},"instructions":{"type":"string","description":"Istruzioni aggiuntive per l''estrazione"}},"required":["text","schema"]}'),
  ('tool_analyze_video', 'analyze_video', 'Analizza video: estrae frame chiave, li analizza con vision AI, trascrive audio', 'media', '{"type":"object","properties":{"path":{"type":"string","description":"Percorso del file video"},"prompt":{"type":"string","description":"Domanda o istruzione per l''analisi"},"extract_audio":{"type":"boolean","default":true,"description":"Estrarre e trascrivere audio"},"num_frames":{"type":"number","default":4,"description":"Numero di frame da analizzare"}},"required":["path"]}');
